### ISSUE TITLE
Run Shell Script Error

### ISSUE THREAD

**Issue by jzrskc** [dral3x/automator-combine-images#1]
I tried combining images with Automator and followed your instructions, but I got this message:

<img width="277" alt="Screenshot 2022-11-22 at 17 17 49" src="https://user-images.githubusercontent.com/13225841/203367612-bb3d71e3-f994-40e8-a426-cc47fa86e1f9.png">

MacOS: 13.0.1
After half an hour of trying, any help is appreciated.

**Comment by dral3x** [comment]
@jzrskc I haven't upgraded to Ventura yet, but looks like `convert` is not installed on your mac.

You can install it via [brew](https://brew.sh/) (`brew install imagemagick`).
If you're running on an M1 mac, then update also the workflow last "Run Shell Command" step, 
replacing `/usr/local/bin/convert` with `/opt/homebrew/bin/convert`

**Comment by jzrskc** [comment]
Thanks for your help, is works now!
